[DEFAULT]
URL = https://test.actingoffice.com/admin

USERNAME = yash.rajpurohit.capsitech@gmail.com
Password = Z/x.c,vmbnA's;dlfkgjh@1234567890

#URL = https://appuat.actingoffice.com/
#USERNAME = demo.admin@actingoffice.com
#Password = AdminAO@1947



